app = "deepcheckai"   # your Fly.io app name
primary_region = "jnb"   # Johannesburg, South Africa

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  ENVIRONMENT = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false   # keep running, no idle shutdown
  auto_start_machines = true
  min_machines_running = 1     # ensures it stays alive
  concurrency = { type = "connections", hard_limit = 25, soft_limit = 20 }

[checks]
  [checks.health]
    type = "http"
    interval = "15s"
    timeout = "2s"
    grace_period = "20s"
    method = "GET"
    path = "/api/health"
